### ISSUE TITLE
Add support of 5.13.x.x bamboo version

### ISSUE THREAD

**Issue by Sergey-Russiyan** [allure-framework/allure-bamboo-plugin#13]
Hi guys.

Can you add support of more actual bamboo versions, e.g. version 5.13.x.x?

According to official Atlassian page:
https://marketplace.atlassian.com/plugins/ru.yandex.qatools.allure.allure-bamboo-plugin/server/overview
plugin supports: "... Bamboo Server 5.6.0 - 5.11.4.1 ..."
Our DevOps refuses to install officially unsupported yet, plugins.

Thank you in advance.
Sergey R.

**Comment by vania-pooh** [comment]
Updated setting to 5.13.2. Hope it works (didn't test).
