### ISSUE TITLE
Atlassian Marketplace - Allure

### ISSUE THREAD

**Issue by dmhalejr** [allure-framework/allure-bamboo-plugin#2]
I can't actually upload plugins since our company is on a hosted version of Bamboo. Is there an ETA on the possibility of Allure being added to the Atlassian Marketplace in the near future? 

Search: 
https://marketplace.atlassian.com/search?q=allure

**Comment by dmhalejr** [comment]
@vania-pooh I forgot to kick myself to kick you. :smile: Any update on this?

**Comment by vania-pooh** [comment]
@dmhalejr will work on this next week. Sorry for these delays but the end of the year was really difficult.

**Comment by dmhalejr** [comment]
@vania-pooh No worries. Thanks for this!

**Comment by vania-pooh** [comment]
@dmhalejr resubmitted plugin for approval to Atlassian Marketplace.

**Comment by vania-pooh** [comment]
@dmhalejr still on review.... :(

**Comment by vania-pooh** [comment]
@dmhalejr still waiting for feedback from Atlassian side.

**Comment by dmhalejr** [comment]
@vania-pooh Thanks for the updating! I feel like I need to buy you guys a beer for the trouble. :beers:

**Comment by vania-pooh** [comment]
@dmhalejr we did it. https://marketplace.atlassian.com/plugins/ru.yandex.qatools.allure.allure-bamboo-plugin

**Comment by dmhalejr** [comment]
@vania-pooh Looks great that this item is now available on the Atlassian Marketplace as a server solution, but my company is still utilizing the cloud solution of Bamboo currently. 

Hate to trouble you again, but is it in the realm of possibility to get this item to be a cloud based solution as well?

**Comment by vania-pooh** [comment]
Hmm, according to this query: https://marketplace.atlassian.com/plugins/app/bamboo/popular?cost=free&hosting=cloud there're only 4 free plugins for cloud. And I don't see any instruction how to get plugin supported by the cloud installations. If you could provide us such information we would try to get Allure added to the cloud.
