### ISSUE TITLE
Error at stage of publishing allure report artifact: Unable to publish artifact [Allure Report]: null

### ISSUE THREAD

**Issue by pavlovoilov** [allure-framework/allure-bamboo-plugin#3]
Version of plugin installed: 1.1
While execution task "Allure Report" everything seems to be good, logs:
```
simple	21-Apr-2015 14:40:21	Starting task 'Allure Report' of type 'ru.yandex.qatools.allure.allure-bamboo-plugin:allureplugin'
simple	21-Apr-2015 14:40:21	-----------
simple	21-Apr-2015 14:40:21	Allure Task
simple	21-Apr-2015 14:40:21	-----------
simple	21-Apr-2015 14:40:21	Trying to generate Allure 1.4.11 using /var/lib/atlassian/bamboo/xml-data/build-dir/3047425/ZD-UT-JOB1 as base directory with pattern = server/ui-test/target/allure-results
simple	21-Apr-2015 14:40:21	Allure data will be saved to /var/lib/atlassian/bamboo/xml-data/build-dir/3047425/ZD-UT-JOB1/allure
simple	21-Apr-2015 14:40:21	Processing Allure XML files
simple	21-Apr-2015 14:40:22	Unpacking Allure report face
simple	21-Apr-2015 14:40:22	Successfully generated Allure report
simple	21-Apr-2015 14:40:22	Finished task 'Allure Report' with result: Success
```
But when Bamboo tries to publish Allure report artifact, it fails without normal explanation what wrong has happened:
```
simple	21-Apr-2015 14:40:36	Running post build plugin 'Artifact Copier'
simple	21-Apr-2015 14:40:36	Publishing an artifact: Allure Report
error	21-Apr-2015 14:40:36	Unable to publish artifact [Allure Report]: null
simple	21-Apr-2015 14:40:36	Finished publishing of artifact Job artifact: [Allure Report], pattern: [**] anchored at: [allure-results] in 0s
```
Allure-results folder contains valid xml file, tried to "mvn site" locally and everything works good.

Bamboo version is:
```
 Continuous integration powered by Atlassian Bamboo version 5.7.0 build 5714 - 05 Nov 14
```
Also, there is nothing special in tasks settings.
![allure-report-task](https://cloud.githubusercontent.com/assets/6242313/7256403/98e458cc-e857-11e4-9d7e-113834164804.png)

Please, contact me if some more details is needed.
Thanks!

**Comment by vania-pooh** [comment]
@pavlovoilov are you using proxies to connect to Internet from Bamboo server?

**Comment by pavlovoilov** [comment]
@vania-pooh no, we use only NAT.

**Comment by vania-pooh** [comment]
Seems to be related to https://github.com/allure-framework/allure-cli/issues/33

**Comment by pavlovoilov** [comment]
After some experiments we figured out root of the problem.
There are two places for configuring Allure.
First one is to add "Allure Task" to a job and set it to fetch results from "**/allure-results" folder where XML files are stored after tests execution.

![allure task settings](https://cloud.githubusercontent.com/assets/6242313/7370171/da14f158-edc0-11e4-9e54-a2e238d506fa.png)

Second one is on "Artifacts" tab where you should add Allure.
And that is the magic place...
Somehow after parsing XML files, Allure generates "allure" folder that is on the same level as "project.basedir". And "Copy pattern" should be as two stars.
If somebody else has such problem, walk around and check a place where Allure generate the report and point it to that place.

![allure artifact settings](https://cloud.githubusercontent.com/assets/6242313/7370238/4d265308-edc1-11e4-9860-cdd6be41c840.png)

Maybe this can help for somebody.
Nevertheless, thanks for fast response.
Closing this issue.
