### ISSUE TITLE
Allure plugin is not supported for Bamboo versions 5.9+

### ISSUE THREAD

**Issue by pavlovoilov** [allure-framework/allure-bamboo-plugin#4]
Hi Guys,
Thanks for the great job you done on Allure report, it really helps our team!

However, our devops are going to move to newer version of Bamboo (v. 5.9.2) and noticed that there is no support of Allure report plugin on it...
Are you going to make updates and support newer Bamboo versions?

**Comment by vania-pooh** [comment]
@pavlovoilov we're not using Bamboo so if you could test whether current code works with new Bamboo version it would be great. After that I could just modify compatibilty settings on Atlassian web site.

**Comment by jdesulme** [comment]
Hi is there an update for this plugin? I noticed that there's compatibility up until 5.9.4. But we're upgrading to 5.9.7 which I don't expect to have that many change given that it's 3 minor versions out of date.

**Comment by vania-pooh** [comment]
Updated compatibility settings on Marketplace. Please test whether it works.

**Comment by anejnz** [comment]
Hi is there an update for this plugin to b compatible for 5.10?

**Comment by vania-pooh** [comment]
Updated compatibility setting. Please report if something does not work.
