### ISSUE TITLE
Unable to publish artifact [Allure Report]: ........ /allure does not exist.

### ISSUE THREAD

**Issue by sahas-** [allure-framework/allure-bamboo-plugin#7]
Below is my setup.

<img width="702" alt="screen shot 2016-04-08 at 9 40 58 am" src="https://cloud.githubusercontent.com/assets/10361685/14387856/e17e8a56-fd70-11e5-9e5b-508270c2a224.png">

<img width="1211" alt="screen shot 2016-04-08 at 10 01 57 am" src="https://cloud.githubusercontent.com/assets/10361685/14387870/f538393e-fd70-11e5-99c6-9f2e7bd6d230.png">

Everything works fine as long as tests pass.
When there is any failure, reports do get generated based on Bamboo logs but this plug-in doesn't generate report and hence /allure directory is not found as an Artifact.

<img width="739" alt="screen shot 2016-04-08 at 10 05 01 am" src="https://cloud.githubusercontent.com/assets/10361685/14387970/6c58c038-fd71-11e5-9290-84350ea9cc28.png">

<img width="1419" alt="screen shot 2016-04-08 at 10 05 10 am" src="https://cloud.githubusercontent.com/assets/10361685/14387972/6edc7e44-fd71-11e5-8b37-8936c6004abf.png">

**Comment by vania-pooh** [comment]
@sahas- : This plugin only generates Allure report based on XML files generated by another Bamboo task (e.g. tests run by some language automation tool like Maven). I think the issue is that in case of failure the tool of your choice does not create respective XML file. Which test framework are you using?

**Comment by sahas-** [comment]
@vania-pooh I'm using wdio which intern uses mocha. When I test this failure case locally, I do see "allure-results" gets gets populated with results. The same case with Bamboo as well. Does that help?

**Comment by just-boris** [comment]
@sahas- as I see from your screenshot, you set Allure version to 1.3.9. Try to change it to latest `1.4.23`. Wdio works fine only with latest `1.4.x` Allure versions

**Comment by sahas-** [comment]
Thanks, it works.
Plus, we need to add Allure part of  **"Final tasks"** so that it runs regardless of test success/failure.
